/*
 * The MIT License
 *
 * Copyright 2015 David-MSJ.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package soundlab;

import java.awt.Color;

/**
 *
 * @author David-MSJ
 */
public class Quiz extends javax.swing.JPanel {
    private int question1Selection;
    private String question2String;
    private int question3Selection;
    
    /**
     * Creates new form Quiz
     */
    public Quiz() {
        initComponents();
    }

    public int getQuestion1Selection() {
        return question1Selection;
    }

    public String getQuestion2String() {
        return question2String;
    }

    public int getQuestion3Selection() {
        return question3Selection;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        question1ButtonGroup = new javax.swing.ButtonGroup();
        question3ButtonGroup = new javax.swing.ButtonGroup();
        titleLabel = new javax.swing.JLabel();
        question1_1 = new javax.swing.JLabel();
        question1_2 = new javax.swing.JLabel();
        question1_3 = new javax.swing.JLabel();
        question1Button1 = new javax.swing.JRadioButton();
        question1Button2 = new javax.swing.JRadioButton();
        question1Button3 = new javax.swing.JRadioButton();
        question1Button4 = new javax.swing.JRadioButton();
        question2_1 = new javax.swing.JLabel();
        question2_2 = new javax.swing.JLabel();
        question2_3 = new javax.swing.JLabel();
        question2_4 = new javax.swing.JLabel();
        question2TextField = new javax.swing.JTextField();
        question3_3 = new javax.swing.JLabel();
        question3_2 = new javax.swing.JLabel();
        question3_1 = new javax.swing.JLabel();
        question3Button1 = new javax.swing.JRadioButton();
        question3Button2 = new javax.swing.JRadioButton();
        submitButton = new javax.swing.JButton();
        resultText = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 200));
        setMinimumSize(new java.awt.Dimension(800, 200));
        setPreferredSize(new java.awt.Dimension(800, 200));

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        titleLabel.setText("Quiz");

        question1_1.setText("Of the following ranges, which");

        question1_2.setText("range accounts for the full spect-");

        question1_3.setText("rum of human hearing?");

        question1ButtonGroup.add(question1Button1);
        question1Button1.setText("1Hz - 100kHz");
        question1Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question1Button1ActionPerformed(evt);
            }
        });

        question1ButtonGroup.add(question1Button2);
        question1Button2.setText("20Hz - 20kHz");
        question1Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question1Button2ActionPerformed(evt);
            }
        });

        question1ButtonGroup.add(question1Button3);
        question1Button3.setText("50Hz - 50kHz");
        question1Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question1Button3ActionPerformed(evt);
            }
        });

        question1ButtonGroup.add(question1Button4);
        question1Button4.setText("25Hz - 25kHz");
        question1Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question1Button4ActionPerformed(evt);
            }
        });

        question2_1.setText("If you're listening to 98.1FM");

        question2_2.setText("(98.1 MHz), what is the wavelen-");

        question2_3.setText("-th of the radio waves?");

        question2_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        question2_4.setText("Answer to the Nearest Hundreth.");

        question2TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                question2TextFieldFocusLost(evt);
            }
        });
        question2TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                question2TextFieldKeyTyped(evt);
            }
        });

        question3_3.setText("louder it is.");

        question3_2.setText("amplitude of a sound wave, the");

        question3_1.setText("True or False: The higher the");

        question3ButtonGroup.add(question3Button1);
        question3Button1.setText("True");
        question3Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question3Button1ActionPerformed(evt);
            }
        });

        question3ButtonGroup.add(question3Button2);
        question3Button2.setText("False");
        question3Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question3Button2ActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        resultText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(question1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(question2_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(question1Button1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(question1Button2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(question1Button3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(question1Button4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(question2_4, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(question2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question3_3, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(question3_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(question3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(question3Button1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(question3Button2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitButton)
                        .addGap(24, 24, 24))))
            .addGroup(layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(titleLabel)
                .addGap(47, 47, 47)
                .addComponent(resultText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(question1_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(question1_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(question2_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(question2_2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel)
                    .addComponent(resultText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(question1_1)
                            .addComponent(question2_1))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(question1_2)
                            .addComponent(question2_2))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(question1_3)
                            .addComponent(question2_3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(question3_1)
                        .addGap(0, 0, 0)
                        .addComponent(question3_2)
                        .addGap(1, 1, 1)
                        .addComponent(question3_3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question1Button1)
                    .addComponent(question1Button2)
                    .addComponent(question2_4)
                    .addComponent(question3Button1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(question1Button3)
                    .addComponent(question1Button4)
                    .addComponent(question2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(question3Button2)
                    .addComponent(submitButton))
                .addContainerGap(2, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        int numCorrect = 0;
        Color correctGreen = new Color(50,140,50);

        if(question1Button2.isSelected()) {
            question1_1.setForeground(correctGreen);
            question1_2.setForeground(correctGreen);
            question1_3.setForeground(correctGreen);
            numCorrect++;
        }
        else    {
            question1_1.setForeground(Color.RED);
            question1_2.setForeground(Color.RED);
            question1_3.setForeground(Color.RED);
        }

        if((question2TextField.getText().equals("3.06")) || 
                (question2TextField.getText().equals("3.06m")) || 
                (question2TextField.getText().equals("3.06 m")) || 
                (question2TextField.getText().equals("3.06 meters")) || 
                (question2TextField.getText().equals("3.06meters")))   {
            question2_1.setForeground(correctGreen);
            question2_2.setForeground(correctGreen);
            question2_3.setForeground(correctGreen);
            question2_4.setForeground(correctGreen);
            numCorrect++;
        }
        else    {
            question2_1.setForeground(Color.RED);
            question2_2.setForeground(Color.RED);
            question2_3.setForeground(Color.RED);
            question2_4.setForeground(Color.RED);
        }
        
        if(question3Button1.isSelected())   {
            question3_1.setForeground(correctGreen);
            question3_2.setForeground(correctGreen);
            question3_3.setForeground(correctGreen);
            numCorrect++;
        }
        else    {
            question3_1.setForeground(Color.RED);
            question3_2.setForeground(Color.RED);
            question3_3.setForeground(Color.RED);
        }
        
        if(numCorrect == 3) {
            resultText.setForeground(correctGreen);
            resultText.setText("Good job!");
        }
        else    {
            resultText.setForeground(Color.RED);
            resultText.setText("Try again!");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void question1Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question1Button1ActionPerformed
        question1Selection = 1;
    }//GEN-LAST:event_question1Button1ActionPerformed

    private void question1Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question1Button2ActionPerformed
        question1Selection = 2;
    }//GEN-LAST:event_question1Button2ActionPerformed

    private void question1Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question1Button3ActionPerformed
        question1Selection = 3;
    }//GEN-LAST:event_question1Button3ActionPerformed

    private void question1Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question1Button4ActionPerformed
        question1Selection = 4;
    }//GEN-LAST:event_question1Button4ActionPerformed

    private void question3Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question3Button1ActionPerformed
        question3Selection = 1;
    }//GEN-LAST:event_question3Button1ActionPerformed

    private void question3Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question3Button2ActionPerformed
        question3Selection = 2;
    }//GEN-LAST:event_question3Button2ActionPerformed

    private void question2TextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_question2TextFieldKeyTyped
        question2String = question2TextField.getText();
    }//GEN-LAST:event_question2TextFieldKeyTyped

    private void question2TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_question2TextFieldFocusLost
        question2String = question2TextField.getText();
    }//GEN-LAST:event_question2TextFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton question1Button1;
    private javax.swing.JRadioButton question1Button2;
    private javax.swing.JRadioButton question1Button3;
    private javax.swing.JRadioButton question1Button4;
    private javax.swing.ButtonGroup question1ButtonGroup;
    private javax.swing.JLabel question1_1;
    private javax.swing.JLabel question1_2;
    private javax.swing.JLabel question1_3;
    private javax.swing.JTextField question2TextField;
    private javax.swing.JLabel question2_1;
    private javax.swing.JLabel question2_2;
    private javax.swing.JLabel question2_3;
    private javax.swing.JLabel question2_4;
    private javax.swing.JRadioButton question3Button1;
    private javax.swing.JRadioButton question3Button2;
    private javax.swing.ButtonGroup question3ButtonGroup;
    private javax.swing.JLabel question3_1;
    private javax.swing.JLabel question3_2;
    private javax.swing.JLabel question3_3;
    private javax.swing.JLabel resultText;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
